name: Semantic Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  Release:
    # https://github.community/t/how-do-i-specify-job-dependency-running-in-another-workflow/16482
    #if: github.event_name == 'push' && github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Semantic Release
        run: |
          pip install semantic-release
          pip install poetry
          poetry add --dev python-semantic-release
          semantic-release version -v DEBUG
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
